#!/usr/bin/env bash

# Check if git is installed.
git --version > /dev/null 2>&1
GIT_INSTALLED=$?

if [ $GIT_INSTALLED -ne 0 ]; then
  echo "git is not installed!"
  echo "Please install git and try again"
  exit 0
fi

git clone --bare https://github.com/kaarx/dotfiles.git $HOME/.dots

function config {
   /usr/bin/git --git-dir=$HOME/.dots/ --work-tree=$HOME $@
}

mkdir -p .config-backup
config checkout
if [ $? = 0 ]; then
  echo "Checked out config.";
  else
    echo "Backing up pre-existing dot files.";
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
fi;
config checkout
config config status.showUntrackedFiles no
