#!/usr/bin/env bash

function rdp-params() {
	if [[ ("$#" -ne 1 && "$#" -ne 2)]]; then
		echo "Usage: rdp-params <server>[:port] [username]"
		return 1;
	fi	
	local sec="-sec-nla +sec-rdp"
	local res="/w:1660 /h:1825"
	local params="/cert-ignore /bpp:16 /compression -themes -wallpaper /clipboard /auto-reconnect -glyph-cache"
	local title="/title:$1"
	if [[ "$#" -eq 2 ]]; then
		sec="-sec-rdp /u:$2"
		title="/title:$2@$1"
	fi
	echo "$params $sec $res $title /v:$1"
}

function rdp() {
	if [[ ("$#" -ne 1 && "$#" -ne 2)]]; then
		echo "Usage: rdp <server>[:port] [username]"
		return 1;
	fi

	local params=$(rdp-params $@)
	
	xfreerdp $params #$sec $res $title /v:$server
}

function ssh-tunnel-master () {
	local ssh_server=$1
	# check to see if ssh control master is running, if not start it.
	if ssh -O check $ssh_server >/dev/null 2>&1; then
		echo "Master $ssh_server is already running"
	else
		echo "Master $ssh_server is not running, starting it now"
		ssh -f -N $ssh_server
	fi
}

function rdp-ssh-tunnel() {
	if [[ ("$#" -ne 2 && "$#" -ne 3)]]; then
		echo "Usage : rdp-ssh-tunnel <ssh_server> <rdp_server>[:port] [rdp_user_name]"
		return 1;
	fi

	local ssh_server=$1
	local rdp_server=$2
	local rdp_user_name=$3
	local remote_port="3389"

	# random local port number, pick another if it's in use.
	local local_port=$(( ( RANDOM % 40000 )  + 20000 ))
	while netstat -an | grep -c "[:.]$local_port\s" >/dev/null 2>&1
	do
		local_port=$(( ( RANDOM % 40000 )  + 20000 ))
	done
	
	# check to see if rdp_server contains port
	if echo $rdp_server  | grep -c ":" >/dev/null 2>&1; then
		local tmp=$rdp_server
		rdp_server=$(echo $tmp | cut -d: -f1)
		remote_port=$(echo $tmp | cut -d: -f2)
	fi

	ssh-tunnel-master $ssh_server

	# add local forwarding rules to exiting ssh session
	ssh -O forward -L $local_port:$rdp_server:$remote_port $ssh_server
	rdp localhost:$local_port $rdp_user_name
}

function rdp-proxychains () {
	if [[ ("$#" -ne 2 && "$#" -ne 3)]]; then
		echo "Usage : rdp-proxychains <proxychains_config_file> <rdp_server>[:port] [rdp_user_name]"
		return 1;
	fi
	local params=$(rdp-params ${@:2})
	proxychains4 -f $1 xfreerdp $params
}

function rdp-pom() {
	if [[ ("$#" -ne 1 && "$#" -ne 2)]]; then
		echo "Usage : rdp-pom <rdp_server>[:port] [rdp_user_name]"
		return 1;
	fi
	ssh-tunnel-master pombounce
	rdp-proxychains ~/.proxychains/pombounce.conf $1 $2
}

function rdp-lae() {
	if [[ ("$#" -ne 1 && "$#" -ne 2)]]; then
		echo "Usage : rdp-lae <rdp_server>[:port] [rdp_user_name]"
		return 1;
	fi

	ssh-tunnel-master laebounce
	rdp-proxychains ~/.proxychains/laebounce.conf $1 $2
}